default_language_version:
    python: python3.8
default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8